<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Tiffany Moyeda" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Project 2</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume.pdf">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
        <section id="projects">
  <div class="container">
    <h3>Projects</h3>
    <div class="panel panel-default">
      <div class="panel-body">
      


<p><em>The following data there are 303 items (patients) and 13 predictor variables (age, sex, cholesterol, etc.) The variable to predict is encoded as 0 to 4 where 0 means no heart disease and 1-4 means presence of heart disease. The following varaibles are the ones that I will be focusing on: Sex = (1 = male; 0 = female), thalach = maximum heart rate achieved, cp = chest pain type (0 to 4 where 0 means no heart disease and 1-4 means presence of heart disease), trestbps = resting blood pressure (in mm Hg on admission to the hospital), and chol = serum cholestoral in mg/dl.</em></p>
<pre class="r"><code>heart &lt;- read_csv(&quot;heart.csv&quot;)
head(heart)</code></pre>
<pre><code>## # A tibble: 6 x 14
##     age   sex    cp trestbps  chol   fbs restecg thalach exang oldpeak slope
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1    63     1     3      145   233     1       0     150     0     2.3     0
## 2    37     1     2      130   250     0       1     187     0     3.5     0
## 3    41     0     1      130   204     0       0     172     0     1.4     2
## 4    56     1     1      120   236     0       1     178     0     0.8     2
## 5    57     0     0      120   354     0       1     163     1     0.6     2
## 6    57     1     0      140   192     0       1     148     0     0.4     1
## # … with 3 more variables: ca &lt;dbl&gt;, thal &lt;dbl&gt;, target &lt;dbl&gt;</code></pre>
<pre class="r"><code>#MANOVA
man1&lt;-manova(cbind(thalach, chol, trestbps)~cp, data=heart)
summary(man1)</code></pre>
<pre><code>##            Df   Pillai approx F num Df den Df    Pr(&gt;F)    
## cp          1 0.098003   10.829      3    299 8.961e-07 ***
## Residuals 301                                              
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1) </code></pre>
<pre><code>##  Response thalach :
##              Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## cp            1  13860 13859.9  28.854 1.564e-07 ***
## Residuals   301 144583   480.3                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response chol :
##              Df Sum Sq Mean Sq F value Pr(&gt;F)
## cp            1   4798  4798.3  1.7908 0.1818
## Residuals   301 806503  2679.4               
## 
##  Response trestbps :
##              Df Sum Sq Mean Sq F value Pr(&gt;F)
## cp            1    211  210.54  0.6838 0.4089
## Residuals   301  92681  307.91</code></pre>
<pre class="r"><code>heart%&gt;%group_by(cp)%&gt;%summarize(mean(thalach),mean(chol), mean(trestbps))</code></pre>
<pre><code>## # A tibble: 4 x 4
##      cp `mean(thalach)` `mean(chol)` `mean(trestbps)`
##   &lt;dbl&gt;           &lt;dbl&gt;        &lt;dbl&gt;            &lt;dbl&gt;
## 1     0            141.         250.             132.
## 2     1            162.         245.             128.
## 3     2            156.         243.             130.
## 4     3            156.         237.             141.</code></pre>
<pre class="r"><code>pairwise.t.test(heart$thalach, heart$cp,
                p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  heart$thalach and heart$cp 
## 
##   0       1      2     
## 1 1.2e-09 -      -     
## 2 3.2e-07 0.0713 -     
## 3 0.0013  0.2273 0.9443
## 
## P value adjustment method: none</code></pre>
<p><em>A one-way MANOVA was conducted to determine the effect of the chest pain type on the variables thalach, chol, and trestbps. Since overall MANOVA was significant, follow-up one-way ANOVAs for each dependent variable were conducted. Once the ANOVA was run, it was shown that only the thalach, or the maximum heart rate acheived, was significant. There was 1 MANOVA, 2 ANOVAs, and 4 t-tests performed meaning bonferroni α = .05/8 = 0.00625. Post hoc analysis was performed conducting pairwise t-tests to determine which category of chest pain differed in maximum heart rate. Chest pain level of 0 was determined to differ significantly in terms of maximum heart rate after adjusting for multiple comparisons. </em></p>
<pre class="r"><code>#Randomization test 

male &lt;- heart %&gt;% filter( sex == 1) 
female &lt;- heart %&gt;% filter (sex == 0) 


heart%&gt;%group_by(sex)%&gt;%summarize(s=sd(chol))%&gt;%summarize(diff(s))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `diff(s)`
##       &lt;dbl&gt;
## 1     -22.3</code></pre>
<pre class="r"><code>rand_dist&lt;-vector()
for(i in 1:5000){
new&lt;-data.frame(chol=sample(heart$chol),sex=heart$sex)
rand_dist[i]&lt;-mean(new[new$sex==&quot;0&quot;,]$chol)-
mean(new[new$sex==&quot;1&quot;,]$chol)}
{hist(rand_dist, main=&quot;&quot;,ylab=&quot;&quot;); abline(v = -22.01223,col=&quot;red&quot;) ; abline (v = 22.01223,col=&quot;red&quot;)}</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(rand_dist&lt; -22.0 | rand_dist &gt; 22.0)</code></pre>
<pre><code>## [1] 4e-04</code></pre>
<pre class="r"><code>t.test(data=heart,chol~sex)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  chol by sex
## t = 3.0244, df = 134.39, p-value = 0.002985
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   7.617474 36.406982
## sample estimates:
## mean in group 0 mean in group 1 
##        261.3021        239.2899</code></pre>
<p><em>The null hypothesis is the mean cholesterol level is the same for males and females and the alternative hypothesis is that the mean cholesterol level is differnt between males and females. After running the randomization test and the t-test we are able to see that there is a significant difference between males and females when observing their cholesterol levels. </em></p>
<pre class="r"><code> #Linear Regression

heart$thalach_c &lt;- heart$thalach - mean(heart$thalach)
heart$trestbps_c &lt;- heart$trestbps - mean(heart$trestbps)

fit &lt;- lm(chol ~ thalach_c* trestbps_c, data=heart)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = chol ~ thalach_c * trestbps_c, data = heart)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -125.02  -34.20   -5.40   27.72  323.23 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          246.196995   2.972035  82.838   &lt;2e-16 ***
## thalach_c             -0.008973   0.129965  -0.069   0.9450    
## trestbps_c             0.357710   0.170170   2.102   0.0364 *  
## thalach_c:trestbps_c  -0.003585   0.007647  -0.469   0.6395    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 51.67 on 299 degrees of freedom
## Multiple R-squared:  0.01591,    Adjusted R-squared:  0.006039 
## F-statistic: 1.612 on 3 and 299 DF,  p-value: 0.1867</code></pre>
<pre class="r"><code>ggplotRegression &lt;- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = &quot;lm&quot;, col = &quot;red&quot;) +
  labs(title = paste(&quot;Adj R2 = &quot;,signif(summary(fit)$adj.r.squared, 5),
                     &quot;Intercept =&quot;,signif(fit$coef[[1]],5 ),
                     &quot; Slope =&quot;,signif(fit$coef[[2]], 5),
                     &quot; P =&quot;,signif(summary(fit)$coef[2,4], 5)))
}

ggplotRegression(fit)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>## assumptions
resids&lt;-fit$residuals; fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, col=&quot;red&quot;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>coeftest(fit)[,1:2] ## Normal-theory SEs</code></pre>
<pre><code>##                           Estimate  Std. Error
## (Intercept)          246.196995437 2.972035310
## thalach_c             -0.008973280 0.129964707
## trestbps_c             0.357709672 0.170169644
## thalach_c:trestbps_c  -0.003585077 0.007646917</code></pre>
<pre class="r"><code>coeftest(fit, vcov=vcovHC(fit))[,1:2] ## Robust SEs</code></pre>
<pre><code>##                           Estimate  Std. Error
## (Intercept)          246.196995437 2.982220199
## thalach_c             -0.008973280 0.116801156
## trestbps_c             0.357709672 0.159020831
## thalach_c:trestbps_c  -0.003585077 0.007261943</code></pre>
<p><em>For every 1 mg/dl increase in a patient’s cholesterol there is a decrease of 0.0090 in maximum heart rate when all other variables are constant. For every 1 mg/dl increase in a patient’s cholesterol there is a increase of 0.358 in resting blood pressuure when all other variables are constant. When looking at both variables, there is a 0.0036 decrease in cholesterol. </em></p>
<pre class="r"><code>samp_distn&lt;-replicate(5000, {
boot_dat&lt;-boot_dat&lt;-heart[sample(nrow(heart),replace=TRUE),]
fit2 &lt;- lm(chol ~ thalach_c* trestbps_c, data=heart)
coef(fit2)
})

## Estimated SEs
samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept) thalach_c trestbps_c thalach_c:trestbps_c
## 1           0         0          0                    0</code></pre>
<pre class="r"><code>#Logistic Regression 
data&lt;-heart%&gt;%mutate(y=ifelse(sex==&quot;1&quot;,1,0))
head(data)</code></pre>
<pre><code>## # A tibble: 6 x 17
##     age   sex    cp trestbps  chol   fbs restecg thalach exang oldpeak slope
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1    63     1     3      145   233     1       0     150     0     2.3     0
## 2    37     1     2      130   250     0       1     187     0     3.5     0
## 3    41     0     1      130   204     0       0     172     0     1.4     2
## 4    56     1     1      120   236     0       1     178     0     0.8     2
## 5    57     0     0      120   354     0       1     163     1     0.6     2
## 6    57     1     0      140   192     0       1     148     0     0.4     1
## # … with 6 more variables: ca &lt;dbl&gt;, thal &lt;dbl&gt;, target &lt;dbl&gt;, thalach_c &lt;dbl&gt;,
## #   trestbps_c &lt;dbl&gt;, y &lt;dbl&gt;</code></pre>
<pre class="r"><code>fit3&lt;-glm(y~chol,data=data,family=binomial(link=&quot;logit&quot;))
coeftest(fit3)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##               Estimate Std. Error z value  Pr(&gt;|z|)    
## (Intercept)  2.8452138  0.6489634  4.3842 1.164e-05 ***
## chol        -0.0083242  0.0025272 -3.2939 0.0009882 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit3))</code></pre>
<pre><code>## (Intercept)        chol 
##  17.2052371   0.9917104</code></pre>
<pre class="r"><code>## Confusion matrix
probs&lt;-predict(fit3,type=&quot;response&quot;)
table(predict=as.numeric(probs&gt;.5),truth=data$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict   0   1 Sum
##     0     8   1   9
##     1    88 206 294
##     Sum  96 207 303</code></pre>
<pre class="r"><code>## plot density
data$logit&lt;-predict(fit3,type=&quot;link&quot;)
data%&gt;%ggplot()+geom_density(aes(logit,color=sex,fill=sex), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab(&quot;logit (log-odds)&quot;)+
  geom_rug(aes(logit,color=sex))</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" />
<em>The interaction is predicting the outcome that the patient is male from cholesterol levels. Cholesterol levels decreases log-odds of a patient being a male. Every one-unit increase in cholesterol the odds is mutiplied by 0.992. TPR is 206/209 which is the probabilty of detecting if the patient is really male. TNR is 8/96 which is the probablity that the pateint was ruled a male when in fact they are female. PPV is 206/294 which is the proportion classified as male and who are.</em></p>

      </div>
    </div>
  </div>
</section>

      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
